name: Check Visa Appointments

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  check-appointments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run Docker container
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          # Build the Docker image
          docker build -t appointment-checker .

          # Run the container with environment variables
          docker run \
            -e EMAIL=$EMAIL \
            -e PASSWORD=$PASSWORD \
            -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN \
            -e CHAT_ID=$CHAT_ID \
            appointment-checker
